config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :sessions, only: %i[create new]
  resource :session, only: %i[destroy]

  resources :users do
    resources :followers, controller: 'users/followers', only: %i[index]
    resources :following, controller: 'users/following', only: %i[index]
    resources :posts, controller: 'users/posts', except: %i[index new]
    resources :relationships, controller: 'users/relationships', only: %i[create destroy]
  end

  root to: 'static_pages#home'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include PgSearch

  has_secure_password

  has_many :followers_relationships, class_name: 'Relationship', foreign_key: 'following_id',
                                     inverse_of: :following, dependent: :destroy
  has_many :following_relationships, class_name: 'Relationship', foreign_key: 'follower_id',
                                     inverse_of: :follower, dependent: :destroy
  has_many :followers, through: :followers_relationships, source: :follower
  has_many :following, through: :following_relationships, source: :following
  has_many :notifications, dependent: :destroy
  has_many :posts, dependent: :destroy

  validates :first_name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  has_attached_file :avatar,
                    styles: { medium: '300x300>', thumb: '100x100>' },
                    default_url: ':style/missing-avatar.png'
  validates_attachment_content_type :avatar, content_type: %r{\Aimage/.*\z}

  paginates_per 8

  pg_search_scope :search_by_name,
                  against: %i[first_name last_name],
                  using: {
                    tsearch: { prefix: true },
                    trigram: {},
                    dmetaphone: {}
                  }

  def self.search(query)
    if query.present?
      search_by_name(query)
    else
      all
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def follows?(user)
    Relationship.exists?(follower: self, following: user)
  end

  def posts_by_user(current_user)
    posts = current_user == self ? Post.following_and_mine(self) : self.posts

    posts.includes(:user).by_created_date
  end
end

app/controllers/users/followers_controller.rb
# frozen_string_literal: true

module Users
  class FollowersController < ApplicationController
    before_action :set_user

    # GET /users/1/followers
    def index
      @users = @user.followers.page(params[:page])
    end

    private

    def set_user
      @user = User.find(params[:user_id])
    end
  end
end

app/controllers/users/following_controller.rb
# frozen_string_literal: true

module Users
  class FollowingController < ApplicationController
    before_action :set_user

    # GET /users/1/following
    def index
      @users = @user.following.page(params[:page])
    end

    private

    def set_user
      @user = User.find(params[:user_id])
    end
  end
end

app/controllers/users/posts_controller.rb
# frozen_string_literal: true

module Users
  class PostsController < ApplicationController
    before_action :set_user
    before_action :set_post, only: %i[edit update show destroy]

    # GET /users/1/posts/1
    def show; end

    # GET /users/1/posts/1/edit
    def edit; end

    # POST /users/1/posts
    def create
      @post = @user.posts.build(post_params)

      if @post.save
        redirect_to @user, notice: t('controllers.post.created')
      else
        redirect_to @user
      end
    end

    # PATCH/PUT /users/1/posts/1
    def update
      if @post.update(post_params)
        redirect_to current_user, notice: t('controllers.post.updated')
      else
        redirect_to current_user
      end
    end

    # DELETE /users/1/posts/1
    def destroy
      @post.destroy

      redirect_to current_user, notice: t('controllers.post.destroyed')
    end

    private

    def set_user
      @user = current_user
    end

    def set_post
      @post = current_user.posts.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:message)
    end
  end
end

app/controllers/users/relationships_controller.rb
# frozen_string_literal: true

module Users
  class RelationshipsController < ApplicationController
    before_action :set_follower
    before_action :set_following
    before_action :set_relationship, only: [:destroy]

    # POST /users/1/relationships
    def create
      @relationship = Relationship.new(follower: @follower, following: @following)

      if (@follower != @following) && @relationship.save
        redirect_to @following, notice: t('controllers.relationship.created', username: @following.username)
      else
        redirect_to @following
      end
    end

    # DELETE /users/1/relationships/1
    def destroy
      @relationship.destroy

      redirect_to @following, notice: t('controllers.relationship.destroyed', username: @following.username)
    end

    private

    def set_follower
      @follower = current_user
    end

    def set_following
      @following = User.find(params[:user_id])
    end

    def set_relationship
      @relationship = Relationship.find_by(follower: @follower, following: @following)
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :authenticate_user, only: %i[new create show]
  before_action :set_user, only: %i[show]
  before_action :set_posts, only: %i[show]
  before_action :set_relationship, only: %i[show]

  # GET /users
  def index
    @users = User.search(params[:query]).page(params[:page])
  end

  # GET /users/1
  def show
    @post = current_user.posts.build if user_signed_in?
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = current_user
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: t('controllers.user.created')
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if current_user.update(user_params)
      redirect_to current_user, notice: t('controllers.user.updated')
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    current_user.destroy

    redirect_to users_url, notice: t('controllers.user.destroyed')
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :username,
      :email,
      :password,
      :avatar
    )
  end

  def set_user
    @user = User.find(params[:id]).decorate
  end

  def set_posts
    @posts = @user.posts_by_user(current_user).page(params[:page])
  end

  def set_relationship
    @relationship = Relationship.find_by(follower: current_user, following: @user)
  end
end

app/views/users/_form.html.erb
<%= form_for @user, html: { class: 'ui form' } do |f| %>
  <%= render 'shared/error_messages', object: @user %>
  <div class="required field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="required field">
    <%= f.label :username %>
    <%= f.text_field :username, required: true %>
  </div>
  <div class="required field">
    <%= f.label :email %>
    <%= f.email_field :email, required: true %>
  </div>
  <% if @user.new_record? %>
    <div class="required field">
      <%= f.label :password %>
      <%= f.password_field :password, required: true %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.submit t('views.user.ok'), class: 'ui submit fluid green inverted button' %>
  </div>
<% end %>

app/views/users/_list.html.erb
<div class="users-list">
  <div class="ui four stackable cards">
    <% @users.each do |user| %>
      <%= link_to user_path(user), class: 'card' do %>
        <div class="image">
          <%= image_tag user.avatar.url %>
        </div>
        <div class="content">
          <span class="header"><%= user.full_name %></span>
          <div class="meta">
            <span>@<%= user.username %></span>
          </div>
        </div>
        <div class="extra content">
          <div class="ui green label">
            <%= t('views.user.followers') %>
            <div class="detail"><%= user.followers.count %></div>
          </div>
          <div class="ui green label">
            <%= t('views.user.following') %>
            <div class="detail"><%= user.following.count %></div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= paginate @users %>
</div>

app/views/users/edit.html.erb
<div class="ui stackable centered grid">
  <div class="six wide column">
    <h3 class="ui center aligned header"><%= t('views.user.edit') %></h3>
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="users-list">
  <div class="ui four stackable cards">
    <% @users.each do |user| %>
      <%= link_to user_path(user), class: 'card' do %>
        <div class="image">
          <%= image_tag user.avatar.url %>
        </div>
        <div class="content">
          <span class="header"><%= user.full_name %></span>
          <div class="meta">
            <span>@<%= user.username %></span>
          </div>
        </div>
        <div class="extra content">
          <div class="ui green label">
            <%= t('views.user.followers') %>
            <div class="detail"><%= user.followers.count %></div>
          </div>
          <div class="ui green label">
            <%= t('views.user.following') %>
            <div class="detail"><%= user.following.count %></div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="ui stackable centered grid">
  <div class="six wide column">
    <h3 class="ui center aligned header"><%= t('views.user.new') %></h3>
    <%= render 'form' %>
  </div>
</div>

app/views/users/search.html.erb
<%= render 'list' %>

app/views/users/show.html.erb
<div class="ui stackable grid">
  <div class="six wide column">
    <div class="ui items">
      <div class="item">
        <div class="ui small image">
          <%= image_tag @user.avatar.url(:medium) %>
        </div>
        <div class="middle aligned content">
          <div class="header"><%= @user.full_name %></div>
          <div class="meta">
            <span>@<%= @user.username %></span>
          </div>
          <div class="extra">
            <%= t('views.user.member_since') %> <%= l(@user.created_at, format: :date_only) %>
          </div>
          <div class="follow">
            <%= link_to user_followers_path(@user), class: 'ui green label' do %>
              <%= t('views.user.followers') %>
              <div class="detail"><%= @user.followers.count %></div>
            <% end %>
            <%= link_to user_following_index_path(@user), class: 'ui green label' do %>
              <%= t('views.user.following') %>
              <div class="detail"><%= @user.following.count %></div>
            <% end %>
            <%= render 'users/relationships/form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="ten wide column">
    <% if @user == current_user %>
      <%= render 'users/posts/form' %>
    <% end %>
    <h3 class="ui header">Posts</h3>
    <div class="ui comments">
      <% @posts.each do |post| %>
        <div class="comment">
          <span class="avatar">
            <%= link_to user_path(post.user) do %>
              <%= image_tag post.user.avatar.url(:thumb) %>
            <% end %>
          </span>
          <div class="content">
            <span class="author"><%= link_to "@#{post.user.username}", user_path(post.user) %></span>
            <div class="metadata">
              <span class="date"><%= l(post.created_at, format: :short) %></span>
            </div>
            <div class="text">
              <%= post.message %>
            </div>
            <% if current_user == post.user %>
              <div class="actions">
                <%= link_to t('views.post.edit'), edit_user_post_path(@user, post), class: 'item' %>
                <%= link_to t('views.post.destroy'), user_post_path(@user, post),
                  method: :delete,
                  data: { confirm: t('views.post.delete_confirmation') },
                  class: 'item' %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="pagination">
      <%= paginate @posts %>
    </div>
  </div>
</div>