config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :sessions, only: %i[create new]
  resource :session, only: %i[destroy]

  resources :users do
    resources :followers, controller: 'users/followers', only: %i[index]
    resources :following, controller: 'users/following', only: %i[index]
    resources :posts, controller: 'users/posts', except: %i[index new]
    resources :relationships, controller: 'users/relationships', only: %i[create destroy]
  end

  root to: 'static_pages#home'
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="ui red message">
    <div class="header">A validação falhou:</div>
    <ul class="list">
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, value| %>
  <div class="ui <%= flash_message_class(type) %> message">
    <% if value.kind_of?(Array) %>
      <ul class="list">
        <% value.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% else %>
      <%= value %>
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="ui stackable secondary menu">
  <%= link_to t('views.navbar.home'), home_link, class: 'item' %>
  <% if current_user.present? %>
    <%= link_to t('views.navbar.users'), users_path, class: 'item' %>
  <% end %>
  <div class="right menu">
    <% if current_user.present? %>
      <%= form_tag(users_path, method: :get, class: 'ui transparent icon input') do %>
        <%= text_field_tag :query, nil, placeholder: t('views.navbar.search'), class: 'prompt' %>
        <%= submit_tag '', name: nil, class: 'search link icon', style: 'visibility: hidden' %>
      <% end %>
      <div class="ui notifications dropdown item">
        <i class="alarm outline icon"></i>
        <div class="menu">
          <% @notifications.each do |notification| %>
            <%= link_to '', class: 'item' do %>
              <%= notification.message %>
              <div class="notification-date">
                <%= l(notification.created_at, format: :short) %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="ui user-avatar dropdown item">
        <%= image_tag current_user.avatar.url(:medium), class: 'ui circular avatar image' %>
        <div class="menu">
          <%= link_to t('views.navbar.edit_profile'), edit_user_path(current_user), class: 'item' %>
          <%= link_to t('views.navbar.logout'), session_path, method: :delete, class: 'item' %>
        </div>
      </div>
    <% else %>
      <%= link_to t('views.navbar.login'), new_session_path, class: 'item' %>
    <% end %>
  </div>
</div>